services:
  nextjs:
    build:
      context: ./nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/src
      - /src/node_modules
    working_dir: /src
    command: npm run dev
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://fastapi:8000  # Communicating with FastAPI on port 8000

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finalproject
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"  # Keeping FastAPI on port 8000 internally and externally
    volumes:
      - ./fastapi:/src
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload  # Running FastAPI on port 8000
    depends_on:
      - db
      
volumes:
  postgres_data: