services:
  nextjs:
    build:
      context: ./nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/src
      - /src/node_modules
    working_dir: /src
    command: npm run dev

  db: # This is the database service
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finalproject
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data